name: Docker Image Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_FILE: dockerimg.tar
  IMAGE: picolibc
  HASHED_FILE: .github/packages.txt

jobs:
  cache-maker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone picolibc
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=datetime::$(date -u +'%Y%m%d-%R')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build picolibc container
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: .github/Dockerfile
          tags: ${{ env.IMAGE }}:latest
          outputs: type=docker,dest=${{ env.IMAGE_FILE }}

      - name: Check size
        run: |
          ls -al

      - name: Cache the Docker Image
        uses: actions/cache@v2
        with:
          path: ${{ env.IMAGE_FILE }}
          key: ${{ env.IMAGE_FILE }}-${{ hashFiles(format('{0}', env.HASHED_FILE)) }}-${{ steps.date.outputs.datetime }}
