name: Mac OS X

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # 20M measured cache size (August 2023).
  CCACHE_SIZE: "25M"

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Clone picolibc
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install meson and ninja
        run: pip install meson ninja

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.10
        with:
          key: compilation-${{ runner.os }}-${{ github.job }}
          append-timestamp: false
          max-size: ${{ env.CCACHE_SIZE }}

      - name: MacOS tests
        run: ./.github/do-arm
