name: tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone picolibc'
        uses: actions/checkout@v2
        with:
          path: picolibc

      - name: 'Build picolibc container'
        run: |
          docker build -t picolibc \
            -f picolibc/.github/Dockerfile \
            picolibc

      - name: 'Build on arm'
        run: |
          docker run --rm picolibc ./.github/do-build do-arm-configure build-arm

      - name: 'Test on native'
        run: |
          docker run --rm picolibc ./.github/do-test do-native-configure build-native
